const Colors = ["blue", "red", "yellow", "green"];

const Deck = [
  "blue0",
  "blue1",
  "blue2",
  "blue3",
  "blue4",
  "blue5",
  "blue6",
  "blue7",
  "blue8",
  "blue9",
  "blueDrawTwo",
  "blueReverse",
  "blueSkip",
  "green0",
  "green1",
  "green2",
  "green3",
  "green4",
  "green5",
  "green6",
  "green7",
  "green8",
  "green9",
  "greenDrawTwo",
  "greenReverse",
  "greenSkip",
  "red0",
  "red1",
  "red2",
  "red3",
  "red4",
  "red5",
  "red6",
  "red7",
  "red8",
  "red9",
  "redDrawTwo",
  "redReverse",
  "redSkip",
  "yellow0",
  "yellow1",
  "yellow2",
  "yellow3",
  "yellow4",
  "yellow5",
  "yellow6",
  "yellow7",
  "yellow8",
  "yellow9",
  "yellowDrawTwo",
  "yellowReverse",
  "yellowSkip",
  "blue1",
  "blue2",
  "blue3",
  "blue4",
  "blue5",
  "blue6",
  "blue7",
  "blue8",
  "blue9",
  "blueDrawTwo",
  "blueReverse",
  "blueSkip",
  "green1",
  "green2",
  "green3",
  "green4",
  "green5",
  "green6",
  "green7",
  "green8",
  "green9",
  "greenDrawTwo",
  "greenReverse",
  "greenSkip",
  "red1",
  "red2",
  "red3",
  "red4",
  "red5",
  "red6",
  "red7",
  "red8",
  "red9",
  "redDrawTwo",
  "redReverse",
  "redSkip",
  "yellow1",
  "yellow2",
  "yellow3",
  "yellow4",
  "yellow5",
  "yellow6",
  "yellow7",
  "yellow8",
  "yellow9",
  "yellowDrawTwo",
  "yellowReverse",
  "yellowSkip",
  "wild",
  "wild",
  "wild",
  "wild",
  "drawFour",
  "drawFour",
  "drawFour",
  "drawFour",
];

const Cards = {
  blue0: {
    svg: "/cards/blue0.svg",
    color: "blue",
    hasNumber: true,
    number: 0,
    action: "",
    id: "blue0",
  },
  blue1: {
    svg: "/cards/blue1.svg",
    color: "blue",
    hasNumber: true,
    number: 1,
    action: "",
    id: "blue1",
  },
  blue2: {
    svg: "/cards/blue2.svg",
    color: "blue",
    hasNumber: true,
    number: 2,
    action: "",
    id: "blue2",
  },
  blue3: {
    svg: "/cards/blue3.svg",
    color: "blue",
    hasNumber: true,
    number: 3,
    action: "",
    id: "blue3",
  },
  blue4: {
    svg: "/cards/blue4.svg",
    color: "blue",
    hasNumber: true,
    number: 4,
    action: "",
    id: "blue4",
  },
  blue5: {
    svg: "/cards/blue5.svg",
    color: "blue",
    hasNumber: true,
    number: 5,
    action: "",
    id: "blue5",
  },
  blue6: {
    svg: "/cards/blue6.svg",
    color: "blue",
    hasNumber: true,
    number: 6,
    action: "",
    id: "blue6",
  },
  blue7: {
    svg: "/cards/blue7.svg",
    color: "blue",
    hasNumber: true,
    number: 7,
    action: "",
    id: "blue7",
  },
  blue8: {
    svg: "/cards/blue8.svg",
    color: "blue",
    hasNumber: true,
    number: 8,
    action: "",
    id: "blue8",
  },
  blue9: {
    svg: "/cards/blue9.svg",
    color: "blue",
    hasNumber: true,
    number: 9,
    action: "",
    id: "blue9",
  },
  blueDrawTwo: {
    svg: "/cards/blueDrawTwo.svg",
    color: "blue",
    hasNumber: false,
    number: null,
    action: "drawTwo",
    id: "blueDrawTwo",
  },
  blueReverse: {
    svg: "/cards/blueReverse.svg",
    color: "blue",
    hasNumber: false,
    number: null,
    action: "reverse",
    id: "blueReverse",
  },
  blueSkip: {
    svg: "/cards/blueSkip.svg",
    color: "blue",
    hasNumber: false,
    number: null,
    action: "skip",
    id: "blueSkip",
  },
  green0: {
    svg: "/cards/green0.svg",
    color: "green",
    hasNumber: true,
    number: 0,
    action: "",
    id: "green0",
  },
  green1: {
    svg: "/cards/green1.svg",
    color: "green",
    hasNumber: true,
    number: 1,
    action: "",
    id: "green1",
  },
  green2: {
    svg: "/cards/green2.svg",
    color: "green",
    hasNumber: true,
    number: 2,
    action: "",
    id: "green2",
  },
  green3: {
    svg: "/cards/green3.svg",
    color: "green",
    hasNumber: true,
    number: 3,
    action: "",
    id: "green3",
  },
  green4: {
    svg: "/cards/green4.svg",
    color: "green",
    hasNumber: true,
    number: 4,
    action: "",
    id: "green4",
  },
  green5: {
    svg: "/cards/green5.svg",
    color: "green",
    hasNumber: true,
    number: 5,
    action: "",
    id: "green5",
  },
  green6: {
    svg: "/cards/green6.svg",
    color: "green",
    hasNumber: true,
    number: 6,
    action: "",
    id: "green6",
  },
  green7: {
    svg: "/cards/green7.svg",
    color: "green",
    hasNumber: true,
    number: 7,
    action: "",
    id: "green7",
  },
  green8: {
    svg: "/cards/green8.svg",
    color: "green",
    hasNumber: true,
    number: 8,
    action: "",
    id: "green8",
  },
  green9: {
    svg: "/cards/green9.svg",
    color: "green",
    hasNumber: true,
    number: 9,
    action: "",
    id: "green9",
  },
  greenDrawTwo: {
    svg: "/cards/greenDrawTwo.svg",
    color: "green",
    hasNumber: false,
    number: null,
    action: "drawTwo",
    id: "greenDrawTwo",
  },
  greenReverse: {
    svg: "/cards/greenReverse.svg",
    color: "green",
    hasNumber: false,
    number: null,
    action: "reverse",
    id: "greenReverse",
  },
  greenSkip: {
    svg: "/cards/greenSkip.svg",
    color: "green",
    hasNumber: false,
    number: null,
    action: "skip",
    id: "greenSkip",
  },
  red0: {
    svg: "/cards/red0.svg",
    color: "red",
    hasNumber: true,
    number: 0,
    action: "",
    id: "red0",
  },
  red1: {
    svg: "/cards/red1.svg",
    color: "red",
    hasNumber: true,
    number: 1,
    action: "",
    id: "red1",
  },
  red2: {
    svg: "/cards/red2.svg",
    color: "red",
    hasNumber: true,
    number: 2,
    action: "",
    id: "red2",
  },
  red3: {
    svg: "/cards/red3.svg",
    color: "red",
    hasNumber: true,
    number: 3,
    action: "",
    id: "red3",
  },
  red4: {
    svg: "/cards/red4.svg",
    color: "red",
    hasNumber: true,
    number: 4,
    action: "",
    id: "red4",
  },
  red5: {
    svg: "/cards/red5.svg",
    color: "red",
    hasNumber: true,
    number: 5,
    action: "",
    id: "red5",
  },
  red6: {
    svg: "/cards/red6.svg",
    color: "red",
    hasNumber: true,
    number: 6,
    action: "",
    id: "red6",
  },
  red7: {
    svg: "/cards/red7.svg",
    color: "red",
    hasNumber: true,
    number: 7,
    action: "",
    id: "red7",
  },
  red8: {
    svg: "/cards/red8.svg",
    color: "red",
    hasNumber: true,
    number: 8,
    action: "",
    id: "red8",
  },
  red9: {
    svg: "/cards/red9.svg",
    color: "red",
    hasNumber: true,
    number: 9,
    action: "",
    id: "red9",
  },
  redDrawTwo: {
    svg: "/cards/redDrawTwo.svg",
    color: "red",
    hasNumber: false,
    number: null,
    action: "drawTwo",
    id: "redDrawTwo",
  },
  redReverse: {
    svg: "/cards/redReverse.svg",
    color: "red",
    hasNumber: false,
    number: null,
    action: "reverse",
    id: "redReverse",
  },
  redSkip: {
    svg: "/cards/redSkip.svg",
    color: "red",
    hasNumber: false,
    number: null,
    action: "skip",
    id: "redSkip",
  },
  yellow0: {
    svg: "/cards/yellow0.svg",
    color: "yello",
    hasNumber: true,
    number: 0,
    action: "",
    id: "yellow0",
  },
  yellow1: {
    svg: "/cards/yellow1.svg",
    color: "yello",
    hasNumber: true,
    number: 1,
    action: "",
    id: "yellow1",
  },
  yellow2: {
    svg: "/cards/yellow2.svg",
    color: "yello",
    hasNumber: true,
    number: 2,
    action: "",
    id: "yellow2",
  },
  yellow3: {
    svg: "/cards/yellow3.svg",
    color: "yello",
    hasNumber: true,
    number: 3,
    action: "",
    id: "yellow3",
  },
  yellow4: {
    svg: "/cards/yellow4.svg",
    color: "yello",
    hasNumber: true,
    number: 4,
    action: "",
    id: "yellow4",
  },
  yellow5: {
    svg: "/cards/yellow5.svg",
    color: "yello",
    hasNumber: true,
    number: 5,
    action: "",
    id: "yellow5",
  },
  yellow6: {
    svg: "/cards/yellow6.svg",
    color: "yello",
    hasNumber: true,
    number: 6,
    action: "",
    id: "yellow6",
  },
  yellow7: {
    svg: "/cards/yellow7.svg",
    color: "yello",
    hasNumber: true,
    number: 7,
    action: "",
    id: "yellow7",
  },
  yellow8: {
    svg: "/cards/yellow8.svg",
    color: "yello",
    hasNumber: true,
    number: 8,
    action: "",
    id: "yellow8",
  },
  yellow9: {
    svg: "/cards/yellow9.svg",
    color: "yello",
    hasNumber: true,
    number: 9,
    action: "",
    id: "yellow9",
  },
  yellowDrawTwo: {
    svg: "/cards/yellowDrawTwo.svg",
    color: "yello",
    hasNumber: false,
    number: null,
    action: "drawTwo",
    id: "yellowDrawTwo",
  },
  yellowReverse: {
    svg: "/cards/yellowReverse.svg",
    color: "yello",
    hasNumber: false,
    number: null,
    action: "reverse",
    id: "yellowReverse",
  },
  yellowSkip: {
    svg: "/cards/yellowSkip.svg",
    color: "yello",
    hasNumber: false,
    number: null,
    action: "skip",
    id: "yellowSkip",
  },
  wild: {
    svg: "/cards/wild.svg",
    color: "none",
    hasNumber: false,
    number: null,
    action: "wild",
    id: "wild",
  },
  drawFour: {
    svg: "/cards/drawFour.svg",
    color: "none",
    hasNumber: false,
    number: null,
    action: "drawFour",
    id: "drawFour",
  },
};

module.exports = { Cards, Colors, Deck };
