import { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { v4 } from "uuid";

export default function Home() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>UNO React</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.main}>
          <img src="/logo.png" alt="" />
          <div>
            <h1>UNO REACT</h1>
            <h2>v1.0.0</h2>
          </div>
        </div>
        <button
          onClick={() => {
            router.push(`/game/${v4()}`);
          }}
        >
          CREATE GAME
        </button>
      </main>
    </div>
  );
}
